<?php
/*
Plugin Name: Replace Video In Feed
Plugin URI: https://github.com/ryanburnette/wordpress-replace-video-in-feed
Description: a plugin to replace video embed code generated by wordpress in the feeds
Version: 0.1.0
Author: Ryan Burnette
Author URI: https://ryanburnette.com
License: Apache2
*/
